### ISSUE TITLE
support pronounceable passwords (xkcd-like)

### ISSUE THREAD

**Issue by qmx** [cyplo/genpass#10]
One feature that's pretty neat is generating pronounceable passwords like `battery3-horse4-staple`.

**Comment by cyplo** [comment]
Heya! Thank you so much for contributing this issue I think it's an excellent idea:)

**Comment by cyplo** [comment]
https://www.eff.org/files/2016/07/18/eff_large_wordlist.txt

**Comment by cyplo** [comment]
Heya @qmx - I've just released v`0.3` with initial support for passphrases - let me know if you'll have have chance to take a look :)

you can `cargo install genpass --force` to get the newest version.

**Comment by cyplo** [comment]
I've added some more specific issues now that the passphrases are actually being generated and I am closing this one. Let me know how the current implementation feels :) thanks !
