### ISSUE TITLE
Test entropy of generated passwords

### ISSUE THREAD

**Issue by cyplo** [cyplo/genpass#6]
For the full CLI compiled in release mode. 
Maybe use NIST entropy testing suite ?

**Comment by sts10** [comment]
There's also [zxcvbn](https://github.com/dropbox/zxcvbn) which appears to have [a Rust port](https://github.com/shssoichiro/zxcvbn-rs).

**Comment by cyplo** [comment]
Will definitely take a look, thank you :)
